### ISSUE TITLE
현재 날씨 API 만들기

### ISSUE THREAD

**Issue by DaehunGwak** [DaehunGwak/wiary-backend#1]
### TO-DO

- [x] 초기 스프링 세팅
- [ ] 날씨 api 조사 및 테스트
- [ ] 날씨 api 연동
- [ ] 로컬 날씨 api 만들기

### Spec

- Java 17
- 스프링은 최신
- OpenFeign 사용

**Comment by DaehunGwak** [comment]
### 날씨 api 스펙 조사

- 국내 기상청 공공 데이터 활용 (다른 데이터는 사용량이 작거나 유료화에 특화되어 있음)
- 날씨 api spec: https://www.data.go.kr/data/15084084/openapi.do
- 이 중 초단기실황 조회 api 사용
  - sample: GET `http://apis.data.go.kr/1360000/VilageFcstInfoService/getUltraSrtNcst ?serviceKey=인증키&numOfRows=10&pageNo=1 &base_date=20151201&base_time=0600&nx=55&ny=127`
![image](https://user-images.githubusercontent.com/12469427/195398118-e9c34799-81d7-4f51-bfab-a897aa72e4f4.png)
![image](https://user-images.githubusercontent.com/12469427/195398183-169f088d-bd6a-40d4-86a3-628e4c1f7934.png)

**Comment by DaehunGwak** [comment]
### 기본 로컬 개발환경에서 프로필 지정 및 멀티 프로필 지정 방법

```yml
spring:
  profiles:
    active: local # 기본 프로필 지정으로 로컬에서 개발할때 해당 프로필로 활성화
    group:
      local: local,security # application-local.yml, application-security.yml 프로필 동시활성화 효과
```

### profile test

> SpringBootTest 라 더 경량화 하는 테스트 방법은 더 알아봐야함

```java
@SpringBootTest
@ActiveProfiles("local")
public class ProfileTest {

    @Value("${test-value.something}")
    private String something;

    @Value("${test-value.something-sec}")
    private String somethingSecurity;

    @Test
    public void 프로필그룹_밸류_테스트() {
        assertThat(something).isEqualTo("something");
        assertThat(somethingSecurity).isEqualTo("something-sec");
    }
}
```

**Comment by DaehunGwak** [comment]
웹에서 현재 위치 (위도 경도) 추출하는 법: https://developer.mozilla.org/ko/docs/Web/API/Geolocation_API/Using_the_Geolocation_API
